app:
    createdtime: "2023-05-31"
    dbtype: postgresql
    name: Inventory Management System
    port: 8080
database:
    backuptime: "2023-06-03"
    dbname: inventory_management_system
    host: localhost
    max_idle_conns: 10
    max_open_conns: 100
    password: gobank
    port: 5432
    sslmode: disable
    username: postgres
